name: dice_you_fools
description: Dice, you fools !


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^0.6.0
  meta: ^1.1.6
  equatable: 0.1.6
  bloc: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



